Document: rx51-sensor-reglist
Title: Debian rx51-sensor-reglist Manual
Author: <insert document author here>
Abstract: This manual describes what rx51-sensor-reglist is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rx51-sensor-reglist/rx51-sensor-reglist.sgml.gz

Format: postscript
Files: /usr/share/doc/rx51-sensor-reglist/rx51-sensor-reglist.ps.gz

Format: text
Files: /usr/share/doc/rx51-sensor-reglist/rx51-sensor-reglist.text.gz

Format: HTML
Index: /usr/share/doc/rx51-sensor-reglist/html/index.html
Files: /usr/share/doc/rx51-sensor-reglist/html/*.html

  
